version: '3.1'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    ports:
      - 9200:9200
    environment:
      - ELASTIC_PASSWORD=example
      - KIBANA_PASSWORD=example

      - node.name=es01
      - xpack.security.enabled=false
      - discovery.type=single-node

    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - ./esdata01:/usr/share/elasticsearch/data
      - ./hunspell:/usr/share/elasticsearch/config/hunspell
      
    build: .

    deploy:
      resources:
        limits:
          memory: 256M
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    volumes:
      - ./certs:/usr/share/kibana/config/certs
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=example

  jupyter:
    image: jupyter/tensorflow-notebook
    restart: always
    ports:
      - 31002:8888
    volumes:
      - ./notebooks:/home/jovyan/work